### PR TITLE
predicting citi bikes

### PR DESCRIPTION
**Pull request by AR5678**

### CODE REVIEW

**Review by SoyBison — CHANGES_REQUESTED** [review]
I can't find your submission for the 16th. Could you double check that you committed it? Looks like your last commit was wednesday.

**Comment by AR5678** [comment]
It is taking a while to compress the objects but after it is done - I will
send a pull request

**Comment by AR5678** [comment]
Okay cool then I won't. The shell tells me I am I am 91% way there

**Comment by SoyBison** [comment]
Your github repo says the last commit was 2 days ago

**Review by SoyBison — APPROVED** [review]

**Comment by AR5678** [comment]
yeah I think I committed it but I will try to commit it again

**Pull request closed without merging**
